In [ ]:
# INDIVIDUAL ASSIGNMENT

# STUDY GROUP 4

# NAME: JOYCE EBRUPHIYO ETATA

# WTF ID: WTF/2025/1760

# OUTLOOK MAIL: joycejamesetata@outlook.com



In [ ]:
# QUESTION : Write 40 methods in numpy and pandas and one example  each.

In [ ]:
# 40 METHODS IN NumPy WITH ONE EXAMPLE

In [ ]:
# ARRAY CREATION :This is use to create NumPy arrays in different ways(like lists, but faster and smarter for math).

# METHOD 1. np.array() : Creates a NumPy array from a Python list or tuple, It is use when you already have data.

# EXAMPLE : np.array([1, 2, 3, 4, 9, 0, 16])
import numpy as np
arr = np.array([1, 2, 3, 4, 9, 0, 16])

print(arr)


[ 1  2  3  4  9  0 16]


In [ ]:
# METHOD 2. np.zeros(): It is use to creates an array filled with 0s.

# EXAMPLE : np.zeros(3)
import numpy as np
np.zeros(5)




array([0., 0., 0., 0., 0.])

In [ ]:
# METHOD 3. np.ones(): It is used to creates an array filled with 1s.

# EXAMPLE : np.ones(7)
import numpy as np
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# METHOD 4. np.empty() :It is use to  make an “empty” array (random numbers first)

# EXAMPLE : np.empty(6)

import numpy as np
np.empty(6)

array([1.24e-322, 1.48e-322, 1.73e-322, 3.95e-322, 4.45e-322, 4.20e-322])

In [ ]:
# METHOD 5. np.arange() : It is use to make numbers in a range.

# EXAMPLE : np.arange(0,2,4)
import numpy as np

np.arange(0,2,4)


array([0])

In [ ]:
# METHOD 6. np.linspace() : It is use to make evenly spaced numbers

# EXAMPLE : np.linspace(2, 4, 6, 8)

import numpy as np
np.linspace(2, 4, 6, 8)


array([2. , 2.4, 2.8, 3.2, 3.6, 4. ])

In [ ]:
# METHOD 7. np.eye() : It is use to make an identity matrix (diagonal 1, rest 0)

# EXAMPLE : np.eye(5)

import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# METHOD 8. np.full() : It is use to make an array filled with a number you choose

# EXAMPLE : np.full((3,6), 6)

import numpy as np
np.full((3,6), 6)

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [ ]:
# SHAPE AND STRUCTURE : Look at or change dimensions of arrays.

# METHOD 9. reshape() → Change array shape

# EXAMPLE : np.array([1,2,3,4, 5, 6]).reshape(2,3)

import numpy as np
np.array([1, 2 ,3 ,4, 5, 6]).reshape(2,3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# METHOD 10. flatten() : It is use to turn array into 1D

# EXAMPLE : np.array([[2,4,6],[8,10,12]]).flatten()

import numpy as np
np.array([[2,4,6],[8,10,12]]).flatten()

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
# METHOD 11. ravel() : It is  Like flatten, but more memory efficient

# EXAMPLE : np.array([[2,4,6],[8,10,12]]).ravel()

import numpy as np
np.array([[2,4,6],[8,10,12]]).ravel()

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
# METHOD 12. transpose() : It is use to swap rows and columns

# EXAMPLE : np.array([[2,4,6],[8,10,12]]).transpose()

import numpy as np
np.array([[2,4,6],[8,10,12]]).transpose()



array([[ 2,  8],
       [ 4, 10],
       [ 6, 12]])

In [ ]:
# METHOD 13. ndim : It is use to know the number of dimensions

# EXAMPLE : np.array([[2,4,6],[8,10,12]]).ndim

import numpy as np

np.array([[2,4,6],[8,10,12]]).ndim


2

In [ ]:
# METHOD 14. shape : It tells you the size of an array — how many rows and columns it has.

# EXAMPLE : np.array([[2,4,6],[8,10,12]]).shape

import numpy as np
np.array([[2,4,6],[8,10,12]]).shape

(2, 3)

In [ ]:
# MATHEMATICS AND STATISTICS: Do basic calculations on arrays.
# METHOD 15. sum() : It is use to add all numbers

# EXAMPLE: np.array([1,2,3, 5, 6, 8, 9, 10]).sum()

import numpy as np
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).sum()

np.int64(55)

In [ ]:


# METHOD 16. mean() : It is use to calculate the average

# EXAMPLE: np.array([1,2,3, 5, 6, 8, 9, 10]).mean()

import numpy as np
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).mean()




np.float64(5.5)

In [ ]:
# METHOD 17. median() : It is use to calculate the middle value

# EXAMPLE: np.array([1,2,3, 5, 6, 8, 9, 10]).median()

import numpy as np
print(np.median(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])))

5.5


In [ ]:

# METHOD 17. std() : It is use to calculate  standard deviation

# EXAMPLE: np.array([1,2,3, 5, 6, 8, 9, 10]).std()

import numpy as np
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).std()

np.float64(2.8722813232690143)

In [ ]:

# METHOD 18. var() : It is use to calculate variance

# EXAMPLE: np.array([1,2,3, 5, 6, 8, 9, 10]).var()

import numpy as np
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).var()

np.float64(8.25)

In [ ]:

# METHOD 19. max() : It is use to calculate the largest number

# EXAMPLE: np.array([1,2,3, 5, 6, 8, 9, 10]).max()

import numpy as np
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).max()

np.int64(10)

In [ ]:
# METHOD 20. min() : It is use to calculate the smallest number

# EXAMPLE: np.array([1,2,3, 5, 6, 8, 9, 10]).min()

import numpy as np
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).min()

np.int64(1)

In [ ]:
# METHOD 21. argmax() : It is use to calculate the index largest number

# EXAMPLE: np.array([1,2,3, 5, 6, 8, 9, 10]).argmax()

import numpy as np
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).argmax()

np.int64(9)

In [ ]:
# METHOD 22. argmin() : It is use to calculate the index smallest number

# EXAMPLE: np.array([1,2,3, 5, 6, 8, 9, 10]).argmin()

import numpy as np
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).argmin()

np.int64(0)

In [ ]:
# MATHEMATICAL OPERATIONS : Do mathematical functions easily.


# METHOD 23. sqrt() It is use to find  Square root

# EXAMPLE : np.sqrt([16,225])

import numpy as np
np.sqrt([16,225])

array([ 4., 15.])

In [ ]:
# METHOD 24. exp() : The exp() function is used to calculate the exponential of a number, i.e.,

# EXAMPLE : np.exp([4,2])

import numpy as np
np.exp([4,2])

array([54.59815003,  7.3890561 ])

In [ ]:
# METHOD 26. log() : Calculates the natural logarithm (ln) of each element.

# EXAMPLE : np.log([1, np.e])
import numpy as np

np.log([1, np.e])

array([0., 1.])

In [ ]:
# METHOD 27. abs() : Returns the absolute value of each element.

# EXAMPLE : np.abs([-10, 2])
import numpy as np

np.abs([-10, 3])

array([10,  3])

In [ ]:
# METHOD 28. round() : Rounds each element to a specified number of decimals.

# EXAMPLE : np.round([15.234, 25.567], 2)
import numpy as np

np.round([15.234, 25.567], 2)

array([15.23, 25.57])

In [ ]:
# METHOD 29. where() : Returns elements based on a condition (if condition True → value1 else → value2).

# EXAMPLE : np.where([1,2,3, 4 ] > 2, 1, 0)

import numpy as np

print(np.where(np.array([1, 2, 3, 4]) > 2, 1, 0))


[0 0 1 1]


In [ ]:
# METHOD 30. unique() : Returns the unique values in the array.

# EXAMPLE : np.unique([2,2,4,5])

import numpy as np

np.unique([2,2,4,5])

array([2, 4, 5])

In [ ]:
# METHOD 31. sort() : Sorts the array in ascending order.

# EXAMPLE : np.sort([31,13,25])

import numpy as np

np.sort([31,13,25])

array([13, 25, 31])

In [ ]:
# METHOD 32. clip() : Limits values in the array to a minimum and maximum.

# EXAMPLE : np.clip([11,6,106], 10, 12)

import numpy as np

np.clip([11, 6, 106], 10, 12)

array([11, 10, 12])

In [ ]:
# METHOD 33. concatenate() : Joins two or more arrays.

# EXAMPLE : np.concatenate(([1,2, 6],[3,4, 8]))

import numpy as np
np.concatenate(([1,2, 6],[3,4, 8]))

array([1, 2, 6, 3, 4, 8])

In [ ]:
# METHOD 34. stack() : Stacks arrays vertically.

# EXAMPLE : np.stack(([1,2], [6,8], [3,4]))

import numpy as np

np.stack(([1,2], [6,8],[3,4]))

array([[1, 2],
       [6, 8],
       [3, 4]])

In [ ]:
# METHOD 35. vstack() : Stacks arrays vertically (row-wise).

# EXAMPLE : np.vstack(([1,2], [6,8],[3,4]))

import numpy as np

np.vstack(([1,2], [6,8],[3,4]))

array([[1, 2],
       [6, 8],
       [3, 4]])

In [ ]:
# METHOD 36. hstack() : Stacks arrays horizontally (column-wise).

# EXAMPLE : np.hstack(([1,2], [6,8],[3,4]))

import numpy as np

np.hstack(([1,2], [6,8],[3,4]))

array([1, 2, 6, 8, 3, 4])

In [ ]:
# METHOD 37. dot() : Computes the dot product of two arrays.

# EXAMPLE : np.dot([1,10],[3,41])

np.dot([1,10],[3,41])

np.int64(413)

In [ ]:
# METHOD 38. repeat() : Repeats elements of an array a specified number of times.

# EXAMPLE : np.repeat([1, 2 ,3, 4 , 5], 2)

import numpy as np

np.repeat([1,2,3,4,5], 2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [ ]:
# METHOD 39. cumsum() : Returns the cumulative sum of array elements along a specified axis.

# EXAMPLE : np.cumsum([1,2,3,4, 6, 9])
import numpy as np

np.cumsum([1,2,3,4, 6, 9])

array([ 1,  3,  6, 10, 16, 25])

In [ ]:
# METHOD 40. unique(return_counts=True) : Returns the unique elements of an array and their counts.

# EXAMPLE : np.unique([1,2,2,3,3,3], return_counts=True)

import numpy as np

np.unique([1,2,2,3,3,3], return_counts=True)

(array([1, 2, 3]), array([1, 2, 3]))

In [ ]:
# # 40 METHODS IN PANDAS WITH ONE EXAMPLE

import pandas as pd

df = pd.DataFrame({
    "Name": ["JAMES", "EMMANUEL", "THOMAS", "GIFT"],
    "Age": [25, 30, 35, 38],
    "Subject": ["Mathematics", "Physics", "Chemistry", "Biology"],
    "Score": [80, 90, 85, 95]
})


In [ ]:
# METHOD 1. head() : Shows the first few rows of the dataframe (default 5).

import pandas as pd

df = pd.DataFrame({
    "Name": [
        "JAMES","JAMES",
        "EMMANUEL","EMMANUEL",
        "THOMAS","THOMAS",
        "GIFT","GIFT"
    ],
    "Age": [
        25,25,
        30,30,
        35,35,
        38,38
    ],
    "Subject": [
        "Mathematics", "Physics",
        "Mathematics", "Physics",
        "Mathematics", "Physics",
        "Mathematics", "Physics"
    ],
    "Score": [
        80, 88,
        70, 90,
        60, 65,
        95, 90
    ]
})

# Show first 5 rows
print(df.head())


       Name  Age      Subject  Score
0     JAMES   25  Mathematics     80
1     JAMES   25      Physics     88
2  EMMANUEL   30  Mathematics     70
3  EMMANUEL   30      Physics     90
4    THOMAS   35  Mathematics     60


In [ ]:
# METHOD 2. tail() : Shows the last few rows of the dataframe (default 5).

# EXAMPLE : df.tail()

df.tail()

,Name,Age,Subject,Score
3,EMMANUEL,30,Physics,90
4,THOMAS,35,Mathematics,60
5,THOMAS,35,Physics,65
6,GIFT,38,Mathematics,95
7,GIFT,38,Physics,90


In [ ]:
# METHOD 3. info() : Provides a summary of the dataframe including column types and memory usage.

# EXAMPLE : df.info()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     8 non-null      object
 1   Age      8 non-null      int64 
 2   Subject  8 non-null      object
 3   Score    8 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes


In [ ]:
# METHOD 4. describe() : Returns summary statistics for numeric columns.

# EXAMPLE : df.describe()

df.describe()

,Age,Score
count,8.000000,8.000000
mean,32.000000,79.750000
std,5.291503,13.166516
min,25.000000,60.000000
25%,28.750000,68.750000
50%,32.500000,84.000000
75%,35.750000,90.000000
max,38.000000,95.000000


In [ ]:
# METHOD 5. shape : Returns the number of rows and columns.

# EXAMPLE : df.shape

df.shape

(8, 4)

In [ ]:
# METHOD 6. columns : Returns the column names of the dataframe.

# EXAMPLE : df.columns

df.columns

Index(['Name', 'Age', 'Subject', 'Score'], dtype='object')

In [ ]:
# METHOD 7. index : Returns the row indices of the dataframe.

# EXAMPLE : df.index

df.index

RangeIndex(start=0, stop=8, step=1)

In [ ]:
# METHOD 8. loc[] : Access rows and columns by labels.

# EXAMPLE : df.loc[0]

df.loc[0]

,0
Name,JAMES
Age,25
Subject,Mathematics
Score,80


In [ ]:
# METHOD 9. iloc[] : Access rows and columns by position numbers.

# EXAMPLE : df.iloc[1]

df.iloc[1]

,1
Name,JAMES
Age,25
Subject,Physics
Score,88


In [ ]:
# METHOD 10. at[] : Access a single value by row and column label.

# EXAMPLE : df.at[0, "Age"]

df.at[0, "Age"]

np.int64(25)

In [ ]:
# METHOD 11. iat[] : Access a single value by row and column position.

# EXAMPLE : df.iat[1, 2]

df.iat[1, 2]

'Physics'

In [ ]:
# METHOD 12. isnull() : Detects missing values in the dataframe.

# EXAMPLE : df.isnull()

df.isnull()

,Name,Age,Subject,Score
0,False,False,False,False
1,False,False,False,False
2,False,False,False,False
3,False,False,False,False
4,False,False,False,False
5,False,False,False,False
6,False,False,False,False
7,False,False,False,False


In [ ]:
# METHOD 13. notnull() : Detects non-missing values in the dataframe.

# EXAMPLE : df.notnull()

df.notnull()

,Name,Age,Subject,Score
0,True,True,True,True
1,True,True,True,True
2,True,True,True,True
3,True,True,True,True
4,True,True,True,True
5,True,True,True,True
6,True,True,True,True
7,True,True,True,True


In [ ]:
# METHOD 14. fillna() : Fills missing values with a specified value.

# EXAMPLE : df.fillna(0)

df.fillna(0)

,Name,Age,Subject,Score
0,JAMES,25,Mathematics,80
1,JAMES,25,Physics,88
2,EMMANUEL,30,Mathematics,70
3,EMMANUEL,30,Physics,90
4,THOMAS,35,Mathematics,60
5,THOMAS,35,Physics,65
6,GIFT,38,Mathematics,95
7,GIFT,38,Physics,90


In [ ]:
# METHOD 15. dropna() : Removes rows that contain missing values.

# EXAMPLE : df.dropna()

df.dropna()

,Name,Age,Subject,Score
0,JAMES,25,Mathematics,80
1,JAMES,25,Physics,88
2,EMMANUEL,30,Mathematics,70
3,EMMANUEL,30,Physics,90
4,THOMAS,35,Mathematics,60
5,THOMAS,35,Physics,65
6,GIFT,38,Mathematics,95
7,GIFT,38,Physics,90


In [ ]:
# METHOD 16. drop() : Removes a column or row from the dataframe.

# EXAMPLE : df.drop("Score", axis=1)

df.drop("Score", axis=1)

,Name,Age,Subject
0,JAMES,25,Mathematics
1,JAMES,25,Physics
2,EMMANUEL,30,Mathematics
3,EMMANUEL,30,Physics
4,THOMAS,35,Mathematics
5,THOMAS,35,Physics
6,GIFT,38,Mathematics
7,GIFT,38,Physics


In [ ]:
# METHOD 17. rename() : Renames columns or indices.

# EXAMPLE : df.rename(columns={"Age":"Years"})

df.rename(columns={"Age":"Years"})

,Name,Years,Subject,Score
0,JAMES,25,Mathematics,80
1,JAMES,25,Physics,88
2,EMMANUEL,30,Mathematics,70
3,EMMANUEL,30,Physics,90
4,THOMAS,35,Mathematics,60
5,THOMAS,35,Physics,65
6,GIFT,38,Mathematics,95
7,GIFT,38,Physics,90


In [ ]:
# METHOD 18. astype() : Changes the data type of a column.

# EXAMPLE : df["Age"].astype(float)

df["Age"].astype(float)

,Age
0,25.0
1,25.0
2,30.0
3,30.0
4,35.0
5,35.0
6,38.0
7,38.0


In [ ]:
# METHOD 19. duplicated() : Returns True for duplicate rows.

# EXAMPLE : df.duplicated()

df.duplicated()

,0
0,False
1,False
2,False
3,False
4,False
5,False
6,False
7,False


In [ ]:
# METHOD 20. drop_duplicates() : Removes duplicate rows.

# EXAMPLE : df.drop_duplicates()

df.drop_duplicates()

,Name,Age,Subject,Score
0,JAMES,25,Mathematics,80
1,JAMES,25,Physics,88
2,EMMANUEL,30,Mathematics,70
3,EMMANUEL,30,Physics,90
4,THOMAS,35,Mathematics,60
5,THOMAS,35,Physics,65
6,GIFT,38,Mathematics,95
7,GIFT,38,Physics,90


In [ ]:
# METHOD 21. sort_values() : Sorts the dataframe by a column.

# EXAMPLE : df.sort_values("Age")

df.sort_values("Age")

,Name,Age,Subject,Score
0,JAMES,25,Mathematics,80
1,JAMES,25,Physics,88
2,EMMANUEL,30,Mathematics,70
3,EMMANUEL,30,Physics,90
4,THOMAS,35,Mathematics,60
5,THOMAS,35,Physics,65
6,GIFT,38,Mathematics,95
7,GIFT,38,Physics,90


In [ ]:
# METHOD 22. sort_index() : Sorts the dataframe by row index.

# EXAMPLE : df.sort_index(ascending=False)

df.sort_index(ascending=False)

,Name,Age,Subject,Score
7,GIFT,38,Physics,90
6,GIFT,38,Mathematics,95
5,THOMAS,35,Physics,65
4,THOMAS,35,Mathematics,60
3,EMMANUEL,30,Physics,90
2,EMMANUEL,30,Mathematics,70
1,JAMES,25,Physics,88
0,JAMES,25,Mathematics,80


In [ ]:
# METHOD 23. value_counts() : Counts unique values in a column.

# EXAMPLE : df["Age"].value_counts()

df["Age"].value_counts()

,count
Age,
25,2
30,2
35,2
38,2


In [ ]:
# METHOD 24. nunique() : Returns the number of unique values in each column.

# EXAMPLE : df.nunique()

df.nunique()

,0
Name,4
Age,4
Subject,2
Score,7


In [ ]:
# METHOD 25. sum() : Returns the sum of numeric columns.

# EXAMPLE : df.sum(numeric_only=True)

df.sum(numeric_only=True)

,0
Age,256
Score,638


In [ ]:
# METHOD 26. mean() : Returns the mean of numeric columns.

# EXAMPLE : df.mean(numeric_only=True)

df.mean(numeric_only=True)

,0
Age,32.00
Score,79.75


In [ ]:
# METHOD 27. median() : Returns the median of numeric columns.

# EXAMPLE : df.median(numeric_only=True)

df.median(numeric_only=True)


,0
Age,32.5
Score,84.0


In [ ]:
# METHOD 28. sample() : Randomly selects rows from the dataframe.


# EXAMPLE : df.sample(2)
df.sample(2)

,Name,Age,Subject,Score
3,EMMANUEL,30,Physics,90
7,GIFT,38,Physics,90


In [ ]:
# METHOD 29. apply() : Applies a function to each column or row.

# EXAMPLE : df["Age"].apply(lambda x: x+1)

df["Age"].apply(lambda x: x+1)

,Age
0,26
1,26
2,31
3,31
4,36
5,36
6,39
7,39


In [ ]:
# METHOD 30. map() : Applies a function to a Series.

# EXAMPLE : df["Name"].map(len)

df["Name"].map(len)

,Name
0,5
1,5
2,8
3,8
4,6
5,6
6,4
7,4


In [ ]:
# METHOD 31. applymap() : Applies a function element-wise to a dataframe.

# EXAMPLE : df[["Age","Score"]].applymap(lambda x: x*2)

df[["Age","Score"]].applymap(lambda x: x*2)

/tmp/ipython-input-1422783967.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[["Age","Score"]].applymap(lambda x: x*2)


,Age,Score
0,50,160
1,50,176
2,60,140
3,60,180
4,70,120
5,70,130
6,76,190
7,76,180


In [ ]:
# METHOD 32. merge() : Combines two dataframes based on a column.

# EXAMPLE : pd.merge(df, df, on="Name")

pd.merge(df, df, on="Name")

,Name,Age_x,Subject_x,Score_x,Age_y,Subject_y,Score_y
0,JAMES,25,Mathematics,80,25,Mathematics,80
1,JAMES,25,Mathematics,80,25,Physics,88
2,JAMES,25,Physics,88,25,Mathematics,80
3,JAMES,25,Physics,88,25,Physics,88
4,EMMANUEL,30,Mathematics,70,30,Mathematics,70
5,EMMANUEL,30,Mathematics,70,30,Physics,90
6,EMMANUEL,30,Physics,90,30,Mathematics,70
7,EMMANUEL,30,Physics,90,30,Physics,90
8,THOMAS,35,Mathematics,60,35,Mathematics,60
9,THOMAS,35,Mathematics,60,35,Physics,65


In [ ]:
# METHOD 33. concat() : Concatenates two or more dataframes along rows or columns.

# EXAMPLE : pd.concat([df, df])

pd.concat([df, df])

,Name,Age,Subject,Score
0,JAMES,25,Mathematics,80
1,JAMES,25,Physics,88
2,EMMANUEL,30,Mathematics,70
3,EMMANUEL,30,Physics,90
4,THOMAS,35,Mathematics,60
5,THOMAS,35,Physics,65
6,GIFT,38,Mathematics,95
7,GIFT,38,Physics,90
0,JAMES,25,Mathematics,80
1,JAMES,25,Physics,88


In [ ]:
# METHOD 34. join() : Joins two dataframes on their index.

# EXAMPLE : df.join(df, rsuffix="_r")

df.join(df, rsuffix="_r")

,Name,Age,Subject,Score,Name_r,Age_r,Subject_r,Score_r
0,JAMES,25,Mathematics,80,JAMES,25,Mathematics,80
1,JAMES,25,Physics,88,JAMES,25,Physics,88
2,EMMANUEL,30,Mathematics,70,EMMANUEL,30,Mathematics,70
3,EMMANUEL,30,Physics,90,EMMANUEL,30,Physics,90
4,THOMAS,35,Mathematics,60,THOMAS,35,Mathematics,60
5,THOMAS,35,Physics,65,THOMAS,35,Physics,65
6,GIFT,38,Mathematics,95,GIFT,38,Mathematics,95
7,GIFT,38,Physics,90,GIFT,38,Physics,90


In [ ]:
# METHOD 35. cov() : Calculates the covariance between numeric columns.

# EXAMPLE : df.cov(numeric_only=True)

df.cov(numeric_only=True)

,Age,Score
Age,28.000000,-1.571429
Score,-1.571429,173.357143


In [ ]:
# METHOD 36. clip() : Limits values within a given range.

# EXAMPLE : df["Score"].clip(85, 90)

df["Score"].clip(85, 90)

,Score
0,85
1,88
2,85
3,90
4,85
5,85
6,90
7,90


In [ ]:
# METHOD 37. between() : Checks if values fall between two numbers.

# EXAMPLE : df["Age"].between(26, 34)

df["Age"].between(26, 34)

,Age
0,False
1,False
2,True
3,True
4,False
5,False
6,False
7,False


In [ ]:
# METHOD 38. isin() : Checks if values exist in a given list.

# EXAMPLE : df["Name"].isin(["Anna", "Chris"])

df["Name"].isin(["Anna", "Chris"])

,Name
0,False
1,False
2,False
3,False
4,False
5,False
6,False
7,False


In [ ]:
# METHOD 39. explode() : Splits list-like values into separate rows.

# EXAMPLE :
df2 = pd.DataFrame({
    "Name": ["JOYCE", "THOMAS"],
    "Hobbies": [["Reading", "Eaing"], ["Working", "Travel"]]
})

df2.explode("Hobbies")

,Name,Hobbies
0,JOYCE,Reading
0,JOYCE,Eaing
1,THOMAS,Working
1,THOMAS,Travel


In [ ]:
# METHOD 40. where() : Keeps values that meet a condition and replaces others with NaN.

# EXAMPLE : df["Score"].where(df["Score"] > 85)

df["Score"].where(df["Score"] > 85)

,Score
0,NaN
1,88.0
2,NaN
3,90.0
4,NaN
5,NaN
6,95.0
7,90.0
